/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package web

import io.ktor.server.application.*
import io.ktor.server.response.*
import io.ktor.server.routing.*

fun main(args: Array<String>): Unit = io.ktor.server.netty.EngineMain.main(args)

fun Application.module() {
    configureRouting()
}

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun Application.configureRouting() {
    routing {
        get("/") {
            call.respondText(App().greeting)
        }
    }
}
